version: '3.7'
networks:
  touraxis:
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: touraxis
      MYSQL_USER: touraxis
      MYSQL_PASSWORD: touraxis
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - touraxis
    ports:
      - "3308:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: touraxis
      DB_PASSWORD: touraxis
      DB_DATABASE: touraxis
    depends_on:
      - mysql
    command: yarn dev
    ports:
      - "3000:3000"
    networks:
      - touraxis
volumes:
  mysql: